name: "flair-ner-english-fast-viterbi-decoder"
backend: "python"
default_model_filename: "model.py"
max_batch_size: 0

# This instance group is only here for transparency. Python model access to GPUs is defined in the "model.py" file.
instance_group {
  name: "flair-ner-english-fast-viterbi-decoder"
  count: 1
  gpus: 0
  kind: KIND_GPU
}



input {
  name: "sentence_bytes"
  data_type: TYPE_INT64
  dims: [ -1 ]
  }

input {
  name: "features"
  data_type: TYPE_FP32
  dims: [ -1, -1, 20, 20 ]
  }

input {
  name: "sorted_lengths"
  data_type: TYPE_INT64
  dims: [ -1 ]
  }

output {
  name: "tagged_sentences"
  data_type: TYPE_INT64
  dims: [ -1 ]
  }