name: "flair-ner-english-fast"
platform: "pytorch_libtorch"
version_policy {
  latest {
    num_versions: 1
  }
}
input {
  name: "INPUT__0"
  data_type: TYPE_INT64
  dims: 1
}
input {
  name: "INPUT__1"
  data_type: TYPE_FP32
  dims: 1
  dims: -1
  dims: 2148
}


output {
  name: "OUTPUT__0"
  data_type: TYPE_FP32
  dims: 1
  dims: -1
  dims: 20
  dims: 20
}
output {
  name: "OUTPUT__1"
  data_type: TYPE_INT64
  dims: 1
}
output {
  name: "OUTPUT__2"
  data_type: TYPE_FP32
  dims: 20
  dims: 20
}

instance_group {
  name: "flair-ner-english-fast"
  count: 1
  gpus: 0
  kind: KIND_GPU
}
default_model_filename: "model.pt"

optimization {
  input_pinned_memory {
    enable: true
  }
  output_pinned_memory {
    enable: true
  }
}
backend: "pytorch"