name: "flair-ner-english-fast"
backend: "pytorch"
default_model_filename: "model.pt"
version_policy {
  latest {
    num_versions: 1
  }
}
max_batch_size: 0

instance_group {
  name: "flair-ner-english-fast"
  count: 1
  gpus: 0
  kind: KIND_GPU
}


input {
  name: "INPUT__0"
  data_type: TYPE_INT64
  dims: [1]
}
input {
  name: "INPUT__1"
  data_type: TYPE_FP32
  dims: [ 1, -1, 2148 ]
}


output {
  name: "OUTPUT__0"
  data_type: TYPE_FP32
  dims: [ 1, -1, 20, 20 ]
}
output {
  name: "OUTPUT__1"
  data_type: TYPE_INT64
  dims: [ 1 ]
}
output {
  name: "OUTPUT__2"
  data_type: TYPE_FP32
  dims: [ 20, 20 ]
}